### ISSUE TITLE
There is a question in your Readme

### ISSUE THREAD

**Issue by xiueran** [InhwanBae/SingularTrajectory#2]
when we download datasets ,we find this code "./scripts/download_datasets.sh" don't match with your file name. Can you correct it please？

**Comment by InhwanBae** [comment]
Hi @xiueran ,

Thank you for letting me know. I have corrected all the typos now.

**Comment by InhwanBae** [comment]
I'm closing this issue for now. Feel free to open another issue if you have any further questions!
