### ISSUE TITLE
Some problem with downloading the dataset

### ISSUE THREAD

**Issue by ArcticPole** [InhwanBae/SingularTrajectory#3]
As I run the `./script/download_datasets.sh` 
and then run the example, they always report that `FileNotFoundError: [Errno 2] No such file or directory: './datasets/zara2//train/'`
I check the downloaded dataset, the required dataset is indeed not included.
<img width="275" alt="截屏2024-07-17 下午3 02 19" src="https://github.com/user-attachments/assets/ae420386-0e2c-4b9a-9d5b-1d3b75c09cb5">

**Comment by InhwanBae** [comment]
Hi @ArcticPole,

Thank you for your interest in my work! It seems there is an issue with downloading the official dataset of Social-GAN from Dropbox. You can resolve this issue by downloading and unzipping the [datasets.zip](https://github.com/InhwanBae/SingularTrajectory/releases/download/v0.1/datasets.zip) file from our [Dataset Zoo](https://github.com/InhwanBae/SingularTrajectory/releases/tag/v0.1).

**Comment by InhwanBae** [comment]
I'm closing this issue for now. Feel free to open another issue if you have any further questions!
